### ISSUE TITLE
Problems to install

### ISSUE THREAD

**Issue by LuisPSMachado** [Andrew-AbiMansour/PyGran#8]
I am using Ubuntu 16.04 LTS and I wasn't able to install PyGran.

I am using the following command:
pip install pygran pygran[extras] pygran[analysis] pygran[sim]

The outcome is the following:

Collecting pygran
  Using cached https://files.pythonhosted.org/packages/2c/ee/41befa0979a32ccb9330d7dea64344f8e8beb7f8b7dce0be9ae2030e3809/pygran-1.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-a4koWO/pygran/setup.py", line 97
        sys.stdout.write(f"\r{prefix} {percents}% {suffix}")
                                                          ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-a4koWO/pygran/

Could you help me?

**Comment by anabiman** [comment]
Make sure you're using a recent version of python 3.X.
