### ISSUE TITLE
bug with pygran

### ISSUE THREAD

**Issue by estebanpatino21** [Andrew-AbiMansour/PyGran#9]
Hello, I already have LIGGHTS installed on my computer, run the examples and display them in ParaView and it worked perfectly. Understanding the LIGGGHTS scripts is difficult, that's why I'm trying to install pygran but it's not working.

Traceback (most recent call last):
  File "compaction.py", line 1, in <module>
    from pygran import simulation
ModuleNotFoundError: No module named 'pygran'

I read the comments of the other reported bugs and tried this:

pip uninstall pygran -y
pip install pygran[extra]

To confirm you have the right version, run: python -c "import pygran; print('pygran version = ', pygran.__version__)"

But it still doesn't work:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'pygran' has no attribute '_version_'

Using pip list yes i see pygran 1.4.0

My goal is to run a triaxial compression test of a sand.

I have windows 11 and install ubuntu from the microsoft store:
Ubuntu 2204.2.33.0
In ubuntu I have two versions of python 3.10.6 and 3.7.17, for recommendations I set version 3.7.17 as the default

I hope you can help me with this installation or give me advice to reach my goal.

Thank you so much.

Esteban Patiño
estebanpatino21@gmail.com
Civil engineering student
National university of Colombia

**Comment by anabiman** [comment]
Does this work?
```bash
python -c "import pygran; print('pygran version = ', pygran.__version__)
```

**Comment by estebanpatino21** [comment]
No. The same error appears again:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pygran'

**Comment by anabiman** [comment]
It should work for a fresh installation of pygran. How are you installing pygran? I suggest you purge all pygran installation(s) then run:

```pip install pygran```

If you still cannot import pygran, then your environment might be broken. Are you running this in a virtual environment? Which OS are you using?
